# docker-compose
version: '3'

services:
  webapp:
    image: load-balance-strategies:0.0.1
    build:
      context: ./webapp

  balancer:
    # image: nginx:1.16.0-alpine
    image: nginx
    extra_hosts:
      - kubernetes.docker.internal:127.0.0.1
    ports:
      - "8888:80"
    depends_on:
      - webapp
    volumes:
      - ./balancer/configs/nginx.conf:/etc/nginx/nginx.conf:ro


  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
      - "2003:2003"
    environment:
      - INFLUXDB_DATA_ENGINE=tsm1
      - INFLUXDB_REPORTING_DISABLED=false
      - INFLUXDB_GRAPHITE_0_ENABLED=true
      - INFLUXDB_GRAPHITE_0_DATABASE=graphite
      - INFLUXDB_GRAPHITE_0_BIND_ADDRESS=:2003
      - INFLUXDB_GRAPHITE_PROTOCOL=tcp
      - INFLUXDB_GRAPHITE_BATCH_SIZE=1000
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      - /srv/docker/influxdb/data:/var/lib/influxdb

  # telegraf:
  #   image: telegraf:latest
  #   container_name: telegraf
  #   links:
  #     - influxdb
  #   volumes:
  #     - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    user: "0"
    links:
      - influxdb
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      - /srv/docker/grafana/data:/var/lib/grafana
